add smartPicker for file embeddings
nextcloud/whiteboard pull request #108
Opened 2024-08-07 10:47 UTC by grnd-alt

2024-08-07 11:11 UTC, juliushaertl commented
Two comments without looking at the code yet:
- [ ] Are we somehow able to inject this into the main menubar? Otherwise maybe not for this PR, but would we we able to build our own menubar instead?
- [ ] Picking files is just one aspect, the smart picker also allows to pick different links from other providers like tables/deck. We should make use of the second with `getLinkWithPicker` https://github.com/nextcloud/text/blob/main/src/components/Menu/ActionInsertLink.vue#L218-L229
  - I think the file picker also still makes sense so maybe we can have two buttons Insert a file, Insert smart picker embed

2024-08-07 11:15 UTC, juliushaertl commented
Looks great otherwise 👍

2024-08-08 09:20 UTC, grnd-alt commented
@juliushaertl I've hacked it a little bit so the button is in the tool bar. It is not supported by the lib to add custom elements to that bar. It is though, also required by some other people: https://github.com/excalidraw/excalidraw/issues/7583
so we could think about an upstream contribution, or also do our own toolbar, seems other people have already done it as well. Don't know if it's a good idea to keep my hacked version. Also Excalidraw uses the same Icon for their 'more tools' button as we do for our smart picker button, which we should probably do something about

2024-08-16 18:37 UTC, juliushaertl commented on src/App.tsx
> +		const smartPick = document.createElement('label')
Can we add a tooltip as well?

2024-08-16 18:39 UTC, juliushaertl commented on src/App.tsx
> +			height: 200,
```suggestion
			width: 400,
			height: 200,
```

2024-08-16 18:39 UTC, juliushaertl commented on src/App.tsx
> +			<button className="dropdown-menu-button App-toolbar__extra-tools-trigger" aria-label="Library" aria-keyshortcuts="0" onClick={pickFile} title='Smart Picker'>
```suggestion
			<button className="dropdown-menu-button App-toolbar__extra-tools-trigger" aria-label="Smart picker" aria-keyshortcuts="0" onClick={pickFile} title='Smart picker'>
```

2024-08-16 18:41 UTC, juliushaertl commented on src/App.tsx
> +				<Icon path={mdiShape} size={1} />
I think I missed how the icon is defined but maybe we can use https://pictogrammers.com/library/mdi/icon/slash-forward-box/ instead which is also what Talk uses these days

<img width="265" alt="Screenshot 2024-08-16 at 20 41 33" src="https://github.com/user-attachments/assets/d0cc5a2b-e16d-424b-848d-4d3258a63178">

2024-08-16 18:42 UTC, juliushaertl requested changes
Very nice, works well, just had a few more polishing comments :)

2024-08-19 08:27 UTC, grnd-alt commented on src/App.tsx
> +		const smartPick = document.createElement('label')
Tooltip already exists for me because of the title attribute in `renderSmartPicker` on line 188

2024-08-19 08:51 UTC, juliushaertl approved these changes

2024-08-19 08:51 UTC, merged